name: Api build
on: pull_request

jobs:
  api-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js and dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.4
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build
