name: Api build
on: push

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js and dependencies
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Start PostgreSQL Database
        run: |
          docker compose -f testing.yaml up -d
          sleep 5
      - name: Start migration
        run: npm run test:migrate
      - name: Run integration tests
        run: npm run test:integration

  api-build:
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js and dependencies
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build

  build-docker-image:
    needs: api-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push app Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/task-manager
